### ISSUE TITLE
go vet reports an issue.

### ISSUE THREAD

**Issue by coryschwartz** [testground/sdk-go#7]
This is the issue:
```
 github.com/testground/sdk-go/runtime
runtime/metrics_types.go:55:9: return copies lock value: sync.Pool contains sync.noCopy
```

On this package init logic:

```go
var pools = func() (p [7]sync.Pool) {
	for i := range p {
		p[i].New = func() interface{} {
			return &Metric{Type: MetricType(i), Measures: make(map[string]interface{}, 1)}
		}
	}
	return p
}()
```

**Comment by raulk** [comment]
This is a red herring. It's fine if return copies the values because this is the init block for that variable. It's not a matter of using pointers or not. Slices/arrays are accessed by reference, so a slice/array access on a slice/array of values wouldn't copy the value anyway. It's just that go vet doesn't understand the context of that return.

Proof -- keeping the element type of the array as a value, not a pointer:

```go
package main

import (
	"fmt"
	"sync"
)

var pools [7]sync.Pool

func init() {
        fmt.Println("--- addresses at init ---")
	for i := range pools {
		pools[i] = sync.Pool{}
		fmt.Printf("%p\n", &pools[i])
	}
}

func main() {
        fmt.Println("--- addresses when accessed ---")
	for i := range pools {
		fmt.Printf("%p\n", &pools[i])
	}


}
```

Output:

```
--- addresses at init ---
0x566b00
0x566b28
0x566b50
0x566b78
0x566ba0
0x566bc8
0x566bf0
--- addresses when accessed ---
0x566b00
0x566b28
0x566b50
0x566b78
0x566ba0
0x566bc8
0x566bf0
```

playground: https://play.golang.org/p/9cohxsSQvKb.

---

Since this pool access is in the hot path, I'd like to avoid the extra dereference. So rather than converting the array element type to a pointer, I'm going to move the logic to an `init()` function to pacify go vet's tantrum on the return.
